<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="Skills Network Logo">
    </a>
</p>

# 1D Numpy in Python

Estimated time needed: **40** minutes

## Objectives

After completing this lab you will be able to:

*   Import and use the `numpy` library
*   Perform operations with `numpy`


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-thttps://op/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01: 20px">
    <ul>
        <li>
            <a href="#What-is-Numpy?">What is Numpy?</a>
            <ul>
                <li><a href="#Type">Type</a></li>
                <li><a href="#Assign-Value">Assign Value</a></li>
                <li><a href="#Slicing">Slicing</a></li>
                <li><a href="#Assign-Value-with-List">Assign Value with List</a></li>
                <li><a href="#Other-Attributes">Other Attributes</a></li>
            </ul>
        </li>
        <li>
            <a href="#Numpy-Array-Operations">Numpy Array Operations</a>
            <ul>
                <li><a href="#Array-Addition">Array Addition</a></li>
                <li><a href="#Array-Multiplication">Array Multiplication</a></li>
                <li><a href="#Product-of-Two-Numpy-Arrays">Product of Two Numpy Arrays</a></li>
                <li><a href="#Dot-Product">Dot Product</a></li>
                <li><a href="#Adding-Constant-to-a-Numpy-Array">Adding Constant to a Numpy Array</a></li>
            </ul>
        </li>
        <li><a href="#Mathematical-Functions">Mathematical Functions</a></li>
        <li><a href="#Linspace">Linspace</a></li>
    </ul>

</div>

<hr>


## What is Numpy?


NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices. NumPy stands for Numerical Python and it is an open source project. The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.

It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing `numpy`:


In [42]:
# import numpy library

import numpy as np 

We then cast the list as follows:


In [43]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

Each element is of the same type, in this case integers:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneNp.png" width="500">


As with lists, we can access each element via a square bracket:


In [44]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


#### Checking NumPy Version

The version string is stored under __version__ attribute.


In [45]:
print(np.__version__)

1.26.1


### Type


If we check the type of the array we get <b>numpy.ndarray</b>:


In [46]:
# Check the type of the array

type(a)

numpy.ndarray

As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the data type of the array’s elements. In this case, it's a 64-bit integer:


In [47]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int32')

### Try it yourself

Check the type of the array and Value type for the given array **c**


In [48]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Enter your code here


<details><summary>Click here for the solution</summary>

```python
type(b)
    
b.dtype 
    
If we examine the attribute dtype we see float 64, as the elements are not integers:
```

</details>



### Assign value


We can change the value of the array. Consider the array <code>c</code>:


In [49]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

We can change the first element of the array to 100 as follows:


In [50]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

We can change the 5th element of the array to 0 as follows:


In [51]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

### Try it yourself

Assign the value 20 for the second element in the given array.


In [52]:
a = np.array([10, 2, 30, 40,50])

# Enter your code here


<details><summary>Click here for the solution</summary>

```python
a[1]=20
a
   
```

</details>


### Slicing


Like lists, we can slice the numpy array. Slicing in python means taking the elements from the given index to another given index.

We pass slice like this: [start:end].The element at end index is not being included in the output.

We can select the elements from 1 to 3 and assign it to a new numpy array <code>d</code> as follows:


In [53]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

We can assign the corresponding indexes to new values as follows:


In [54]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

We can also define the steps in slicing, like this: [start:end:step].


In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


If we don't pass start its considered 0


In [56]:
print(arr[:4])

[1 2 3 4]


If we don't pass end it considers till the length of array.


In [57]:
print(arr[4:])

[5 6 7]


If we don't pass step its considered 1


In [58]:
print(arr[1:5:])

[2 3 4 5]


### Try it yourself

Print the even elements in the given array.


In [59]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1::2])

# Enter your code here

[2 4 6 8]


<details><summary>Click here for the solution</summary>

```python
print(arr[1:8:2])

    
```

</details>


### Assign Value with List


Similarly, we can use a list to select more than one specific index.
The list `select` contains several values:


In [60]:
# Create the index list

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

We can use the list as an argument in the brackets. The output is the elements corresponding to the particular indexes:


In [61]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300, 400])

We can assign the specified elements to a new value. For example, we can assign the values to 100 000 as follows:


In [62]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

### Other Attributes


Let's review some basic array attributes using the array <code>a</code>:


In [63]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

The attribute <code>size</code> is the number of elements in the array:


In [64]:
# Get the size of numpy array

a.size

5

The next two attributes will make more sense when we get to higher dimensions but let's review them. The attribute <code>ndim</code> represents the number of array dimensions, or the rank of the array. In this case, one:


In [65]:
# Get the number of dimensions of numpy array

a.ndim

1

The attribute <code>shape</code> is a tuple of integers indicating the size of the array in each dimension:


In [66]:
# Get the shape/size of numpy array

a.shape

(5,)

### Try it yourself

Find the size ,dimension and shape for the given array **b**


In [67]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

# Enter your code here
print("Size of {} is {}".format(b, b.size))
print("Dimensions of {} is {}".format(b, b.ndim))
print("Shape of {} is {}".format(b, b.shape))

Size of [10 20 30 40 50 60 70] is 7
Dimensions of [10 20 30 40 50 60 70] is 1
Shape of [10 20 30 40 50 60 70] is (7,)


<details><summary>Click here for the solution</summary>

```python
b.size

b.ndim

b.shape

    
```

</details>


### Numpy Statistical Functions


In [68]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [69]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [70]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [71]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [72]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [73]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1

### Try it yourself

Find the sum of maximum and minimum value in the given numpy array


<hr>


In [74]:
c = np.array([-10, 201, 43, 94, 502])

# Enter your code here
print("Sum of max and min value of {} is {}".format(c, c.min()+c.max()))

Sum of max and min value of [-10 201  43  94 502] is 492


<details><summary>Click here for the solution</summary>

```python
max_c = c.max()
max_c
    
min_c = c.min()
min_c
    
    
Sum = (max_c +min_c)
Sum

    
```

</details>


## Numpy Array Operations

You could use arithmetic operators directly between NumPy arrays


### Array Addition



Consider the numpy array <code>u</code>:


In [75]:
u = np.array([1, 0])
u

array([1, 0])

Consider the numpy array <code>v</code>:


In [76]:
v = np.array([0, 1])
v

array([0, 1])

We can add the two arrays and assign it to z:


In [77]:
# Numpy Array Addition

z = np.add(u, v)
z

array([1, 1])

The operation is equivalent to vector addition:


In [78]:
# Plotting functions


import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt


def Plotvec1(u, z, v):
    
    ax = plt.axes() # to generate the full window axes
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)# Add an arrow to the  U Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(u + 0.1), 'u')#Adds the text u to the Axes 
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)# Add an arrow to the  v Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(v + 0.1), 'v')#Adds the text v to the Axes 
    
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')#Adds the text z to the Axes 
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)

  


<class 'ModuleNotFoundError'>: The module 'pyparsing' is included in the Pyodide distribution, but it is not installed.
You can install it by calling:
  await micropip.install("pyparsing") in Python, or
  await pyodide.loadPackage("pyparsing") in JavaScript
See https://pyodide.org/en/stable/usage/loading-packages.html for more details.

In [79]:
# Plot numpy arrays

Plotvec1(u, z, v)

<class 'NameError'>: name 'Plotvec1' is not defined

### Try it yourself

Perform addition operation on the given numpy array arr1 and arr2:


In [80]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Enter your code here
np.add(arr1, arr2)

array([30, 32, 34, 36, 38, 40])

<details><summary>Click here for the solution</summary>

```python
arr3 = np.add(arr1, arr2)
arr3

    
```

</details>


### Array Subtraction


Consider the numpy array a:


In [81]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

Consider the numpy array b:


In [82]:
b = np.array([5, 10, 15])
b

array([ 5, 10, 15])

We can subtract the two arrays and assign it to c:


In [83]:
c = np.subtract(a, b)

print(c)

[ 5 10 15]


### Try it yourself

Perform subtraction operation on the given numpy array arr1 and arr2:


In [84]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Enter your code here
np.subtract(arr1, arr2)

array([-10,  -1,   8,  17,  26,  35])

<details><summary>Click here for the solution</summary>

```python
arr3 = np.subtract(arr1, arr2)
arr3

    
```

</details>


### Array Multiplication


Consider the vector numpy array <code>y</code>:


In [85]:
# Create a numpy array

x = np.array([1, 2])
x

array([1, 2])

In [86]:
# Create a numpy array

y = np.array([2, 1])
y

array([2, 1])

We can multiply every element in the array by 2:


In [87]:
# Numpy Array Multiplication

z = np.multiply(x, y)
z

array([2, 2])

This is equivalent to multiplying a vector by a scaler:


### Try it yourself

Perform multiply operation on the given numpy array arr1 and arr2:


In [88]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])

# Enter your code here
np.multiply(arr1, arr2)

array([ 20,  20,  60, 120, 200, 300])

<details><summary>Click here for the solution</summary>

```python
arr3 = np.multiply(arr1, arr2)
arr3

    
```

</details>


### Array Division


Consider the vector numpy array a:


In [89]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

Consider the vector numpy array b:


In [90]:
b = np.array([2, 10, 5])
b

array([ 2, 10,  5])

We can divide the two arrays and assign it to c:


In [91]:
c = np.divide(a, b)
c

array([5., 2., 6.])

### Try it yourself

Perform division operation on the given numpy array arr1 and arr2:


In [92]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

# Enter your code here
np.divide(arr1, arr2)

array([ 3.33333333,  4.        ,  3.        ,  5.        , 25.        ,
        1.81818182])

<details><summary>Click here for the solution</summary>

```python
arr3 = np.divide(arr1, arr2)
arr3

    
```

</details>


### Dot Product


The dot product of the two numpy arrays <code>u</code> and <code>v</code> is given by:


In [93]:
X = np.array([1, 2])
Y = np.array([3, 2])

In [94]:
# Calculate the dot product

np.dot(X, Y)

7

In [95]:
#Elements of X
print(X[0])
print(X[1])

1
2


In [96]:
#Elements of Y
print(Y[0])
print(Y[1])

3
2


We are performing the dot product which is shown as below


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/dot1.png">


### Try it yourself

Perform dot operation on the given numpy array ar1 and ar2:


In [97]:
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])

# Enter your code here
np.dot(arr1, arr2)

26

<details><summary>Click here for the solution</summary>

```python
arr3 = np.dot(arr1, arr2)
arr3

    
```

</details>


### Adding Constant to a Numpy Array


Consider the following array:


In [98]:
# Create a constant to numpy array

u = np.array([1, 2, 3, -1]) 
u

array([ 1,  2,  3, -1])

Adding the constant 1 to each element in the array:


In [99]:
# Add the constant to array

u + 1

array([2, 3, 4, 0])

The process is summarised in the following animation:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneAdd.gif" width="500">


### Try it yourself

Add Constant 5 to the given numpy array ar:


In [100]:
arr = np.array([1, 2, 3, -1]) 

# Enter your code here
arr + 5

array([6, 7, 8, 4])

<details><summary>Click here for the solution</summary>

```python
arr + 5

    
```

</details>


<hr>


## Mathematical Functions


We can access the value of <code>pi</code> in numpy as follows :


In [101]:
# The value of pi

np.pi

3.141592653589793

We can create the following numpy array in Radians:


In [102]:
# Create the numpy array in radians

x = np.array([0, np.pi/2 , np.pi])

We can apply the function <code>sin</code> to the array <code>x</code> and assign the values to the array <code>y</code>; this applies the sine function to each element in the array:


In [103]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

<hr>


## Linspace


A useful function for plotting mathematical functions is <code>linspace</code>.   Linspace returns evenly spaced numbers over a specified interval. 

 **numpy.linspace(start, stop, num = int value)**
 
start  :  start of interval range

stop   :  end of interval range

num    :  Number of samples to generate.


In [104]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

If we change the parameter <code>num</code> to 9, we get 9 evenly spaced numbers over the interval from -2 to 2:


In [105]:
# Make a numpy array within [-2, 2] and 9 elements

np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

We can use the function <code>linspace</code> to generate 100 evenly spaced samples from the interval 0 to 2π:


In [106]:
# Make a numpy array within [0, 2π] and 100 elements 

x = np.linspace(0, 2*np.pi, num=100)

We can apply the sine function to each element in the array <code>x</code> and assign it to the array <code>y</code>:


In [107]:
# Calculate the sine of x list

y = np.sin(x)

In [108]:
# Plot the result

plt.plot(x, y)

<class 'NameError'>: name 'plt' is not defined

### Try it yourself

 Make a numpy array within [5, 4] and 6 elements


In [109]:
# Enter your code here
np.linspace(5, 4, num=6)

array([5. , 4.8, 4.6, 4.4, 4.2, 4. ])

<details><summary>Click here for the solution</summary>

```python
np.linspace(5, 4, num=6)

    
```

</details>


<hr>


### Iterating 1-D Arrays

Iterating means going through elements one by one.

If we iterate on a 1-D array it will go through each element one by one.


If we execute the numpy array, we get in the array format


In [110]:
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


But if you want to result in the form of the list, then you can use for loop:


In [111]:
for x in arr1:
  print(x)

1
2
3


## Quiz on 1D Numpy Array


Implement the following vector subtraction in numpy: u-v


In [112]:
# Write your code below and press Shift+Enter to execute

u = np.array([1, 0])
v = np.array([0, 1])
print(u-v)

[ 1 -1]


<details><summary>Click here for the solution</summary>

```python
u - v
```

</details>


<hr>


Multiply the numpy array z with -2:


In [113]:
# Write your code below and press Shift+Enter to execute

z = np.array([2, 4])
print(z*-2)

[-4 -8]


<details><summary>Click here for the solution</summary>

```python
-2 * z
```

</details>


<hr>


Consider the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[1, 0, 1, 0, 1]</code>. Cast both lists to a numpy array then multiply them together:


In [114]:
# Write your code below and press Shift+Enter to execute
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
print(a*b)

[1 0 3 0 5]


<details><summary>Click here for the solution</summary>

```python
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
a * b
```

</details>


<hr>


In [115]:
# Import the libraries
import time 
import sys
import numpy as np
await micropip.install("pyparsing") 
import matplotlib.pyplot as plt


def Plotvec2(a,b):
    ax = plt.axes()# to generate the full window axes
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)#Add an arrow to the  a Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)#Add an arrow to the  b Axes with arrow head width 0.05, color blue and arrow head length 0.1
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)
    
    


<class 'NameError'>: name 'micropip' is not defined

Convert the list <code>\[-1, 1]</code> and <code>\[1, 1]</code> to numpy arrays <code>a</code> and <code>b</code>. Then, plot the arrays as vectors using the fuction <code>Plotvec2</code> and find their dot product:


In [116]:
# Write your code below and press Shift+Enter to execute
a = np.array([-1, 1])
b = np.array([1, 1])
Plotvec2(a,b)

<class 'NameError'>: name 'Plotvec2' is not defined

<details><summary>Click here for the solution</summary>

```python


a = np.array([-1, 1])
b = np.array([1, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a,b))

```

</details>


<hr>


Convert the list <code>\[1, 0]</code> and <code>\[0, 1]</code> to numpy arrays <code>a</code> and <code>b</code>. Then, plot the arrays as vectors using the function <code>Plotvec2</code> and find their dot product:


In [117]:
# Write your code below and press Shift+Enter to execute
a = np.array([1, 0])
b = np.array([0, 1])
Plotvec2(a,b)

<class 'NameError'>: name 'Plotvec2' is not defined

<details><summary>Click here for the solution</summary>

```python
a = np.array([1, 0])
b = np.array([0, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a, b))

```

</details>


<hr>


Convert the list <code>\[1, 1]</code> and <code>\[0, 1]</code> to numpy arrays <code>a</code> and <code>b</code>. Then plot the arrays as vectors using the fuction <code>Plotvec2</code> and find their dot product:


In [118]:
# Write your code below and press Shift+Enter to execute
a = np.array([1, 1])
b = np.array([0, 1])
Plotvec2(a,b)

<class 'NameError'>: name 'Plotvec2' is not defined

<details><summary>Click here for the solution</summary>

```python
a = np.array([1, 1])
b = np.array([0, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a, b))

```

</details>


<hr>


Why are the results of the dot product for <code>\[-1, 1]</code> and <code>\[1, 1]</code> and the dot product for <code>\[1, 0]</code> and <code>\[0, 1]</code> zero, but not zero for the dot product for <code>\[1, 1]</code> and <code>\[0, 1]</code>? <p><i>Hint: Study the corresponding figures, pay attention to the direction the arrows are pointing to.</i></p>


In [119]:
# Write your code below and press Shift+Enter to execute
"The vectors used for question 4 and 5 are perpendicular. As a result, the dot product is zero."

'The vectors used for question 4 and 5 are perpendicular. As a result, the dot product is zero.'

<details><summary>Click here for the solution</summary>

```python
The vectors used for question 4 and 5 are perpendicular. As a result, the dot product is zero. 

```

</details>


Convert the list <code>\[1, 2, 3]</code> and <code>\[8, 9, 10]</code> to numpy arrays <code>arr1</code> and <code>arr2</code>. Then perform <code>Addition</code> , <code>Subtraction</code> , <code>Multiplication</code> , <code>Division</code> and <code>Dot Operation</code> on the <code>arr1</code> and <code>arr2</code>.



In [120]:
# Write your code below and press Shift+Enter to execute
arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))
print(np.dot(arr1, arr2))

[ 9 11 13]
[-7 -7 -7]
[ 8 18 30]
[0.125      0.22222222 0.3       ]
56


<details><summary>Click here for the solution</summary>

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

arr3 = np.add(arr1, arr2)
arr3

arr4 = np.subtract(arr1, arr2)
arr4

arr5 = np.multiply(arr1, arr2)
arr5


arr6 = np.divide(arr1, arr2)
arr6

arr7 = np.dot(arr1, arr2)
arr7
```

</details>


Convert the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[6, 7, 8, 9, 10]</code> to numpy arrays <code>arr1</code> and <code>arr2</code>. Then find the even and odd numbers from <code>arr1</code> and <code>arr2</code>.


In [121]:
# Write your code below and press Shift+Enter to execute
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

def even_and_odd_1d_arr(arr):
    even = []
    odd = []
    for i in range(0, arr.size):
        rem = arr[i] % 2
        if rem != 0:
            odd.append(arr[i])
        else:
            even.append(arr[i])
    print("Even numbers in {} are {}".format(arr, even))
    print("Odd numbers in {} are {}".format(arr, odd))

even_and_odd_1d_arr(arr1)
even_and_odd_1d_arr(arr2)

Even numbers in [1 2 3 4 5] are [2, 4]
Odd numbers in [1 2 3 4 5] are [1, 3, 5]
Even numbers in [ 6  7  8  9 10] are [6, 8, 10]
Odd numbers in [ 6  7  8  9 10] are [7, 9]


<details><summary>Click here for the solution</summary>

```python


arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

#Starting index in slice is 1 as first even element(2) in array1 is at index 1
even_arr1 = arr1[1:5:2]
print("even for array1",even_arr1)
    
#Starting index in slice is 0 as first odd element(1) in array1 is at index 0
odd_arr1=arr1[0:5:2]
print("odd for array1",odd_arr1)

#Starting index in slice is 0 as first even element(6) in array2 is at index 0
even_arr2 = arr2[0:5:2]
print("even for array2",even_arr2)
    
    
#Starting index in slice is 1 as first odd element(7) in array2 is at index 1
odd_arr2=arr2[1:5:2]
print("odd for array2",odd_arr2)

```

</details>


<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. 
<hr>


## Author

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01" target="_blank">Joseph Santarcangelo</a>

## Other contributors

<a href="https://www.linkedin.com/in/jiahui-mavis-zhou-a4537814a?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Mavis Zhou</a>

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description                 |
| ----------------- | ------- | ---------- | ---------------------------------- |
| 2023-11-02 | 2.3 | Abhishek Gagneja | Instructions updated |
| 2022-03-08        | 2.2     | Niveditha  | Modified and added practice problem|
| 2022-01-10        | 2.1     | Malika     | Removed the readme for GitShare    |
| 2020-08-26        | 2.0     | Lavanya    | Moved lab to course repo in GitLab |
|                   |         |            |                                    |
|                   |         |            |                                    |

<hr/>

## <h3 align="center"> © IBM Corporation 2023. All rights reserved. <h3/>
